from database import db
from models import DEFAULT_BADGES
from auth import pwd_context
from datetime import datetime, timezone, timedelta
import uuid
import logging

logger = logging.getLogger(__name__)


async def seed_data():
    count = await db.auctions.count_documents({})
    if count > 0:
        return
    logger.info("Seeding database...")

    demo_id = str(uuid.uuid4())
    maria_id = str(uuid.uuid4())
    admin_id = str(uuid.uuid4())
    await db.users.insert_many([
        {"id": demo_id, "name": "Carlos López", "email": "carlos@lapopo.es", "password_hash": pwd_context.hash("demo123"), "is_admin": False, "rating_avg": 0, "rating_count": 0, "plan": "free", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": maria_id, "name": "María García", "email": "maria@lapopo.es", "password_hash": pwd_context.hash("demo123"), "is_admin": False, "rating_avg": 0, "rating_count": 0, "plan": "free", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": admin_id, "name": "Admin Lapopo", "email": "admin@lapopo.es", "password_hash": pwd_context.hash("admin123"), "is_admin": True, "rating_avg": 0, "rating_count": 0, "plan": "pro", "created_at": datetime.now(timezone.utc).isoformat()},
    ])

    now = datetime.now(timezone.utc)
    seeds = [
        {"id": str(uuid.uuid4()), "title": "Camara Canon EOS 500D - Perfecta", "description": "Camara reflex Canon EOS 500D en perfecto estado. Incluye objetivo 18-55mm, cargador y bolsa.", "images": ["https://images.unsplash.com/photo-1588768904397-cb062c91ba55?auto=format&fit=crop&q=80&w=600"], "starting_price": 45.0, "current_price": 67.50, "buy_now_price": 120.0, "duration": "3d", "end_time": (now + timedelta(days=2, hours=5)).isoformat(), "category": "Electrónica", "location": "Madrid", "delivery_type": "shipping", "seller_id": demo_id, "seller_name": "Carlos López", "bids": [{"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 50.0, "timestamp": (now - timedelta(hours=5)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 67.50, "timestamp": (now - timedelta(hours=2)).isoformat()}], "bid_count": 2, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=1)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "iPhone 13 - 128GB Azul", "description": "iPhone 13 en color azul, 128GB. Pantalla y bateria al 92%. Sin arañazos. Incluye caja original.", "images": ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600"], "starting_price": 200.0, "current_price": 245.0, "buy_now_price": 400.0, "duration": "7d", "end_time": (now + timedelta(days=5, hours=12)).isoformat(), "category": "Electrónica", "location": "Barcelona", "delivery_type": "both", "seller_id": maria_id, "seller_name": "María García", "bids": [{"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 220.0, "timestamp": (now - timedelta(hours=10)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 245.0, "timestamp": (now - timedelta(hours=3)).isoformat()}], "bid_count": 2, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=2)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Bicicleta de montaña Scott Scale", "description": "Bicicleta MTB Scott Scale 970 talla L. Cuadro de aluminio, frenos de disco hidraulicos.", "images": ["https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&q=80&w=600"], "starting_price": 150.0, "current_price": 185.0, "buy_now_price": None, "duration": "3d", "end_time": (now + timedelta(hours=18)).isoformat(), "category": "Deporte", "location": "Valencia", "delivery_type": "pickup", "seller_id": demo_id, "seller_name": "Carlos López", "bids": [{"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 170.0, "timestamp": (now - timedelta(hours=8)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 185.0, "timestamp": (now - timedelta(hours=1)).isoformat()}], "bid_count": 2, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=1, hours=6)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Tabla de Surf 6'2 - Perfecta para Canarias", "description": "Tabla de surf shortboard 6'2. Ideal para las olas de Canarias. Incluye quillas y funda.", "images": ["https://images.unsplash.com/photo-1675008814982-a18b8efb7e7e?auto=format&fit=crop&q=80&w=600"], "starting_price": 80.0, "current_price": 95.0, "buy_now_price": 150.0, "duration": "7d", "end_time": (now + timedelta(days=4)).isoformat(), "category": "Deporte", "location": "Tenerife", "delivery_type": "pickup", "seller_id": maria_id, "seller_name": "María García", "bids": [{"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 95.0, "timestamp": (now - timedelta(hours=6)).isoformat()}], "bid_count": 1, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=3)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "PlayStation 5 + 2 Mandos", "description": "PS5 con lector de discos. Incluye 2 mandos DualSense y 3 juegos fisicos.", "images": ["https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&q=80&w=600"], "starting_price": 250.0, "current_price": 310.0, "buy_now_price": 450.0, "duration": "3d", "end_time": (now + timedelta(days=1, hours=8)).isoformat(), "category": "Electrónica", "location": "Gran Canaria", "delivery_type": "both", "seller_id": demo_id, "seller_name": "Carlos López", "bids": [{"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 280.0, "timestamp": (now - timedelta(hours=12)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 310.0, "timestamp": (now - timedelta(hours=4)).isoformat()}], "bid_count": 2, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=2)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Mesa de comedor vintage roble", "description": "Preciosa mesa de comedor estilo vintage en madera de roble macizo. 160x90cm.", "images": ["https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=600"], "starting_price": 120.0, "current_price": 120.0, "buy_now_price": None, "duration": "7d", "end_time": (now + timedelta(days=6)).isoformat(), "category": "Hogar", "location": "Sevilla", "delivery_type": "pickup", "seller_id": maria_id, "seller_name": "María García", "bids": [], "bid_count": 0, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=1)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Vestido vintage años 70", "description": "Vestido original de los años 70 en perfecto estado. Talla S/M. Estampado floral unico.", "images": ["https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&q=80&w=600"], "starting_price": 15.0, "current_price": 22.50, "buy_now_price": 45.0, "duration": "24h", "end_time": (now + timedelta(hours=6)).isoformat(), "category": "Moda", "location": "Fuerteventura", "delivery_type": "both", "seller_id": maria_id, "seller_name": "María García", "bids": [{"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 18.0, "timestamp": (now - timedelta(hours=15)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 22.50, "timestamp": (now - timedelta(hours=7)).isoformat()}], "bid_count": 2, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(hours=18)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Coleccion 50 vinilos rock clasico", "description": "Coleccion de 50 vinilos de rock clasico. Beatles, Pink Floyd, Led Zeppelin, Queen.", "images": ["https://images.unsplash.com/photo-1563552744114-78ff178ac8de?auto=format&fit=crop&q=80&w=600"], "starting_price": 1.0, "current_price": 35.0, "buy_now_price": None, "duration": "3d", "end_time": (now + timedelta(days=1, hours=3)).isoformat(), "category": "Otros", "location": "La Palma", "delivery_type": "pickup", "seller_id": demo_id, "seller_name": "Carlos López", "bids": [{"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 15.0, "timestamp": (now - timedelta(hours=30)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 25.0, "timestamp": (now - timedelta(hours=15)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": maria_id, "user_name": "María García", "amount": 35.0, "timestamp": (now - timedelta(hours=5)).isoformat()}], "bid_count": 3, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=2)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Sillon Eames replica - Como nuevo", "description": "Replica del famoso sillon Eames Lounge Chair. Piel sintetica negra, estructura de nogal.", "images": ["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&q=80&w=600"], "starting_price": 1.0, "current_price": 55.0, "buy_now_price": None, "duration": "7d", "end_time": (now + timedelta(days=5, hours=20)).isoformat(), "category": "Hogar", "location": "Málaga", "delivery_type": "pickup", "seller_id": maria_id, "seller_name": "María García", "bids": [{"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 30.0, "timestamp": (now - timedelta(hours=40)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 55.0, "timestamp": (now - timedelta(hours=10)).isoformat()}], "bid_count": 2, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=2)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Patinete electrico Xiaomi Pro 2", "description": "Patinete electrico Xiaomi Mi Electric Scooter Pro 2. 45km de autonomia.", "images": ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&q=80&w=600"], "starting_price": 1.0, "current_price": 1.0, "buy_now_price": 180.0, "duration": "24h", "end_time": (now + timedelta(hours=20)).isoformat(), "category": "Motor", "location": "Tenerife", "delivery_type": "pickup", "seller_id": demo_id, "seller_name": "Carlos López", "bids": [], "bid_count": 0, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(hours=4)).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Lote libros ciencia ficcion", "description": "Lote de 20 libros de ciencia ficcion. Asimov, Clarke, Philip K. Dick.", "images": ["https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=600"], "starting_price": 5.0, "current_price": 12.50, "buy_now_price": None, "duration": "3d", "end_time": (now + timedelta(hours=10)).isoformat(), "category": "Libros", "location": "Gran Canaria", "delivery_type": "both", "seller_id": maria_id, "seller_name": "María García", "bids": [{"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 8.0, "timestamp": (now - timedelta(hours=20)).isoformat()}, {"id": str(uuid.uuid4()), "user_id": demo_id, "user_name": "Carlos López", "amount": 12.50, "timestamp": (now - timedelta(hours=5)).isoformat()}], "bid_count": 2, "status": "active", "winner_id": None, "winner_name": None, "created_at": (now - timedelta(days=2, hours=14)).isoformat()},
    ]
    await db.auctions.insert_many(seeds)
    await db.settings.insert_one({"key": "payments_enabled", "value": False})
    badges = []
    for b in DEFAULT_BADGES:
        badge = dict(b)
        badge["id"] = str(uuid.uuid4())
        badge["created_at"] = datetime.now(timezone.utc).isoformat()
        badges.append(badge)
    await db.badges.insert_many(badges)
    logger.info(f"Seeded {len(seeds)} auctions, 3 users, settings, and {len(badges)} badges")
